### ISSUE TITLE
commitの対象ファイル名の抽出不良

### ISSUE THREAD

**Issue by graycat27** [Yui-KitamuraLLC/workflows#5]
`echo /home/runner/work/JPSCore/JPSCore/target/jpscore-1.0-SNAPSHOT.jar`
```
commit
with:
    files: /home/runner/work**/JPSCore/JPSCore**/target/jpscore-1.0-SNAPSHOT.jar
```

![image](https://user-images.githubusercontent.com/64903817/213910674-7a47ebd6-fabc-4410-a6be-cb40d41cc9e1.png)

**Comment by graycat27** [comment]
https://github.com/Yui-KitamuraLLC/workflows/blob/main/.github/workflows/mavenBuildCommit.yml#L109
固定値"workflow"ではなく、repoName

**Comment by yui-Kitamura** [comment]
fixed.

**Comment by graycat27** [comment]
thx for work.
Fixed version worked well👏
